### ISSUE TITLE
Hi, could you provide the complete code? Thanks

### ISSUE THREAD

**Issue by YuWang0431** [emrysxw/DGI-SLNN#1]
Hi, could you provide the complete code? Thanks

**Comment by emrysxw** [comment]
Thanks for your attention. We have already provided all the necessary code in this repository. All you need to do is click the provided URL to download the open-source dataset, and perform minimal preprocessing. Could you please specify any additional code requirements you might have?

**Comment by YuWang0431** [comment]
Thank you very much for your reply. I have tried to run this code, but I cannot get the paper of the project through the link you gave. I am very interested in your research. If possible, can you share your paper with me? Thank you. My email address is 2021200025@mails.cust.edu.cn

**Comment by emrysxw** [comment]
Our paper has been officially published online. I am glad to share the link with you: https://journals.aps.org/prapplied/abstract/10.1103/PhysRevApplied.22.014023. If you find our work interesting or helpful, please feel free to cite it.
